import 'dart:convert';
import 'package:firebase_ai/firebase_ai.dart';
import 'package:flutter/material.dart';
import '../models/budget_model.dart';
import '../models/expense_model.dart';

/// [AiReceiptResult] represents the structured output parsed from a physical receipt.
/// Contains basic information like transaction type, reference name, amount, and category.
class AiReceiptResult {
  /// Whether this receipt represents an income (e.g., payslip) or an expense.
  final bool isIncome;
  /// The name of the merchant, shop, or source of the transaction.
  final String reference;
  /// The total numeric amount found on the receipt.
  final double amount;
  /// The best-matching category mapped from the app's available categories.
  final String category;

  const AiReceiptResult({
    required this.isIncome,
    required this.reference,
    required this.amount,
    required this.category,
  });
}

/// [AIAnalysisResult] holds the comprehensive financial analysis generated by Gemini.
/// It contains text insights and structured data for charting purposes.
class AIAnalysisResult {
  /// A textual summary, warnings, and tips based on the user's spending habits.
  final String insights;
  
  // Data structures for rendering Pie Charts and Bar Charts
  final Map<String, double> expensesPie;
  final List<double> expensesWeekly;
  final Map<String, double> incomePie;
  final List<double> incomeWeekly;
  final Map<String, double> bothPie;
  final List<Map<String, double>> bothWeekly;

  AIAnalysisResult({
    required this.insights,
    required this.expensesPie,
    required this.expensesWeekly,
    required this.incomePie,
    required this.incomeWeekly,
    required this.bothPie,
    required this.bothWeekly,
  });
}

/// [AIService] acts as the bridge to Firebase AI (Gemini model).
/// Responsible for parsing receipts and generating analytical financial insights.
class AIService {
  /// Analyzes spending data using Firebase AI Logic (Gemini) and returns
  /// structured insights and chart data for incomes, expenses, and both.
  /// 
  /// Takes a list of [records], [budgets], and the [month] string to contextualize the prompt.
  Future<AIAnalysisResult?> analyzeSpendingWithCharts({
    required List<ExpenseModel> records,
    required List<BudgetModel> budgets,
    required String month,
  }) async {
    try {
      // Initialize the Gemini 3.5 Flash model
      final model = FirebaseAI.googleAI().generativeModel(
        model: 'gemini-3.5-flash',
      );

      // Build a text context of the user's budgets to feed to the AI
      final budgetLines = budgets.map((b) {
        return '  • ${b.category}: budget RM${b.allocatedAmount.toStringAsFixed(2)}';
      }).join('\n');

      // Build a text context of all transaction records to feed to the AI
      final recordsLines = records.map((r) {
        final type = r.isIncome ? 'INCOME' : 'EXPENSE';
        return '  • ${r.date.day} ${r.date.month}: $type | ${r.category} | "${r.reference}" | RM${r.amount.toStringAsFixed(2)}';
      }).join('\n');

      // Construct the main prompt enforcing a strict JSON response format
      final prompt = '''
You are a helpful personal finance AI advisor analyzing a user's transactions for the month of $month.

MONTHLY BUDGETS SET:
$budgetLines

INCOME AND EXPENSE TRANSACTIONS:
$recordsLines

Please analyze the data and generate a JSON response with the following format. Ensure that it is valid JSON. Return ONLY the JSON string. Do not wrap in markdown code blocks like ```json.

JSON format:
{
  "insights": "Personalized text insights with 3 sections: 📊 Overview, ⚠️ Watch Out (consider the monthly budgets here), 💡 Tip. In Malaysian Ringgit (RM). Do not use markdown headers.",
  "expenses": {
    "pieChart": {
      "Food": 150.0,
      "Shopping": 200.0
      // Include actual categories and totals from the transactions list
    },
    "weeklyBars": [
      // Total expenses for Week 1 (days 1-7), Week 2 (days 8-14), Week 3 (days 15-21), Week 4 (days 22-end)
      100.0, 50.0, 120.0, 80.0
    ]
  },
  "income": {
    "pieChart": {
      "Earned": 3000.0,
      "Investment": 500.0
      // Include actual categories and totals from the transactions list
    },
    "weeklyBars": [
      // Total incomes for Week 1 (days 1-7), Week 2 (days 8-14), Week 3 (days 15-21), Week 4 (days 22-end)
      1000.0, 500.0, 2000.0, 0.0
    ]
  },
  "both": {
    "pieChart": {
      "Expenses": 350.0,
      "Income": 3500.0
    },
    "weeklyBars": [
      // Week 1, Week 2, Week 3, Week 4 values for expenses and incomes
      { "expenses": 100.0, "income": 1000.0 },
      { "expenses": 50.0, "income": 500.0 },
      { "expenses": 120.0, "income": 2000.0 },
      { "expenses": 80.0, "income": 0.0 }
    ]
  }
}
''';

      // Send the prompt to the Gemini model and await the response
      final response =
          await model.generateContent([Content.text(prompt)]);
      final text = response.text?.trim() ?? '';

      // Extract JSON payload safely by finding the outer brackets
      var cleanText = text;
      final startIndex = cleanText.indexOf('{');
      final endIndex = cleanText.lastIndexOf('}');
      if (startIndex != -1 && endIndex != -1 && endIndex > startIndex) {
        cleanText = cleanText.substring(startIndex, endIndex + 1);
      }
      cleanText = cleanText.trim();

      // Decode the cleaned JSON string into a Dart Map
      final data = jsonDecode(cleanText) as Map<String, dynamic>;

      // Safely extract the insights string
      final insights = data['insights'] as String? ?? 'No insights.';

      // Safely extract and type-cast the expenses chart data
      final expData = data['expenses'] as Map<String, dynamic>? ?? {};
      final expPie = Map<String, double>.from(
          (expData['pieChart'] as Map? ?? {}).map((k, v) =>
              MapEntry(k.toString(), (v as num).toDouble())));
      final expWeekly = List<double>.from(
          (expData['weeklyBars'] as List? ?? [0.0, 0.0, 0.0, 0.0])
              .map((v) => (v as num).toDouble()));

      // Safely extract and type-cast the income chart data
      final incData = data['income'] as Map<String, dynamic>? ?? {};
      final incPie = Map<String, double>.from(
          (incData['pieChart'] as Map? ?? {}).map((k, v) =>
              MapEntry(k.toString(), (v as num).toDouble())));
      final incWeekly = List<double>.from(
          (incData['weeklyBars'] as List? ?? [0.0, 0.0, 0.0, 0.0])
              .map((v) => (v as num).toDouble()));

      // Safely extract and type-cast the combined (both) chart data
      final bothData = data['both'] as Map<String, dynamic>? ?? {};
      final bothPie = Map<String, double>.from(
          (bothData['pieChart'] as Map? ?? {}).map((k, v) =>
              MapEntry(k.toString(), (v as num).toDouble())));
      final bothWeeklyList = List<Map<String, double>>.from(
          (bothData['weeklyBars'] as List? ?? []).map((item) {
        final map = item as Map? ?? {};
        return {
          'expenses': ((map['expenses'] ?? 0.0) as num).toDouble(),
          'income': ((map['income'] ?? 0.0) as num).toDouble(),
        };
      }));

      // Return the fully populated analysis object
      return AIAnalysisResult(
        insights: insights,
        expensesPie: expPie,
        expensesWeekly: expWeekly,
        incomePie: incPie,
        incomeWeekly: incWeekly,
        bothPie: bothPie,
        bothWeekly: bothWeeklyList,
      );
    } catch (e) {
      // Handle parsing or network errors gracefully
      debugPrint('AIService.analyzeSpendingWithCharts error: $e');
      return null;
    }
  }

  /// Legacy support for generating basic string-based spending analysis.
  /// Used if the charting data is not required.
  Future<String> analyzeSpending({
    required Map<String, double> expensesByCategory,
    required Map<String, double> incomeByCategory,
    required List<BudgetModel> budgets,
    required String month,
  }) async {
    try {
      // Initialize the Gemini 3.5 Flash model
      final model = FirebaseAI.googleAI().generativeModel(
        model: 'gemini-3.5-flash',
      );

      // Calculate total expenses, income, and savings rate
      final totalExpenses =
          expensesByCategory.values.fold(0.0, (a, b) => a + b);
      final totalIncome =
          incomeByCategory.values.fold(0.0, (a, b) => a + b);
      final savings = totalIncome - totalExpenses;
      final savingsRate = totalIncome > 0
          ? ((savings / totalIncome) * 100).toStringAsFixed(1)
          : 'N/A';

      // Build budget comparison context
      final budgetLines = budgets.map((b) {
        final spent = expensesByCategory[b.category] ?? 0;
        final pct = b.allocatedAmount > 0
            ? ((spent / b.allocatedAmount) * 100).toStringAsFixed(0)
            : '0';
        return '  • ${b.category}: spent RM${spent.toStringAsFixed(2)} / budget RM${b.allocatedAmount.toStringAsFixed(2)} ($pct%)';
      }).join('\n');

      // Build income context
      final incomeLines = incomeByCategory.isEmpty
          ? '  • No income recorded'
          : incomeByCategory.entries
              .map((e) => '  • ${e.key}: RM${e.value.toStringAsFixed(2)}')
              .join('\n');

      // Construct the text-only prompt
      final prompt = '''
You are a helpful personal finance advisor reviewing a user's spending for $month.

INCOME BREAKDOWN:
$incomeLines
Total Income: RM${totalIncome.toStringAsFixed(2)}

EXPENSE BREAKDOWN (vs monthly budget):
$budgetLines
Total Expenses: RM${totalExpenses.toStringAsFixed(2)}

NET SAVINGS: RM${savings.toStringAsFixed(2)} (savings rate: $savingsRate%)

Please provide a concise, friendly analysis in 3 short sections:
1. 📊 Overview (1–2 sentences summarising the month)
2. ⚠️ Watch Out (highlight any categories over or near their monthly budget, since budgets given are per month)
3. 💡 Tip (one actionable money-saving suggestion)

Keep it short, warm, and in Malaysian Ringgit (RM). Do NOT use markdown headers — just the emoji labels.
''';

      // Request content generation and return the string response
      final response =
          await model.generateContent([Content.text(prompt)]);
      return response.text?.trim() ??
          'AI was unable to generate insights this time.';
    } catch (e) {
      debugPrint('AIService.analyzeSpending error: $e');
      return 'AI insights are unavailable.';
    }
  }

  /// Uses Gemini AI to analyse raw OCR text from a receipt and return
  /// structured data: record type, reference name, total amount, and category.
  Future<AiReceiptResult?> analyzeReceiptText({
    required String rawText,
    required List<String> availableExpenseCategories,
    required List<String> availableIncomeCategories,
  }) async {
    try {
      // Initialize the Gemini 3.5 Flash model
      final model = FirebaseAI.googleAI().generativeModel(
        model: 'gemini-3.5-flash',
      );

      // Join categories into strings for prompt contextualization
      final expCats = availableExpenseCategories.join(', ');
      final incCats = availableIncomeCategories.join(', ');

      // Construct a highly strict prompt instructing the AI how to parse the receipt
      final prompt = '''
You are a smart receipt parser for Malaysian receipts (Bahasa Malaysia and English). Analyze the following OCR text extracted from a receipt image and extract key financial information accurately.

RAW OCR TEXT FROM RECEIPT:
$rawText

Available expense categories: $expCats
Available income categories: $incCats

Return ONLY a valid JSON object (no markdown, no explanation, no code blocks) with these exact fields:
{
  "isIncome": false,
  "reference": "Shop or source name",
  "amount": 0.00,
  "category": "One of the provided categories that best fits"
}

Extraction Rules:
1. "isIncome": Set to true ONLY if this is a salary slip, payslip, bank credit notice, or payment received document. Regular shop/restaurant/petrol station receipts are expenses → false.

2. "reference": Extract the merchant/business name, employer name, or income source. Keep it under 30 characters.

3. "amount": Find the FINAL TOTAL amount paid or NET PAY/SALARY. Extract only the numeric value. Use the LAST occurrence if multiple totals appear.

4. "category": Choose the BEST matching category from the provided categories based on the merchant/source type.
   - For payslips/salaries, choose the best income category (e.g. "Earned").
   - For expenses, map restaurants to "Food", supermarkets to "Groceries", petrol to "Transport", etc.
   - If you cannot confidently select a category, you MUST choose "Others".
   The category MUST exactly match one of: $expCats (for expenses) or $incCats (for income).

5. If you cannot confidently extract the value, use safe defaults: isIncome=false, reference=first non-empty line, amount=0, category="Others".
''';

      // Send prompt to AI and fetch response
      final response = await model.generateContent([Content.text(prompt)]);
      var text = response.text?.trim() ?? '';

      // Extract JSON by finding the first '{' and last '}'
      final startIndex = text.indexOf('{');
      final endIndex = text.lastIndexOf('}');
      if (startIndex != -1 && endIndex != -1 && endIndex > startIndex) {
        text = text.substring(startIndex, endIndex + 1);
      }
      text = text.trim();

      // Decode string into Map
      final data = jsonDecode(text) as Map<String, dynamic>;

      // Construct the AiReceiptResult ensuring safe type-casting
      return AiReceiptResult(
        isIncome: (data['isIncome'] as bool?) ?? false,
        reference: (data['reference'] as String?) ?? 'Unknown',
        amount: (data['amount'] != null)
            ? (double.tryParse(data['amount'].toString()) ?? 0.0)
            : 0.0,
        category: (data['category'] as String?) ??
            (availableExpenseCategories.isNotEmpty
                ? availableExpenseCategories.first
                : 'Other'),
      );
    } catch (e) {
      debugPrint('AIService.analyzeReceiptText error: $e');
      
      // Fallback mechanism: perform manual, regex-based parsing if the AI model fails
      // This ensures the app still works (graceful degradation)
      final lines = rawText.split('\n').map((e) => e.trim()).where((e) => e.isNotEmpty).toList();
      
      // Attempt to guess the reference from the first couple lines
      String ref = 'Unknown';
      if (lines.length > 1) {
        ref = lines.first.toUpperCase().contains('RECEIPT') ? lines[1] : lines.first;
      }
      
      // Attempt to find any monetary value format in the OCR text
      double total = 0.0;
      final RegExp numRegex = RegExp(r'\$?\s*(\d+\.\d{2})');
      for (final line in lines) {
        final match = numRegex.firstMatch(line);
        if (match != null) {
          final val = double.tryParse(match.group(1)!);
          if (val != null) total = val; 
        }
      }
      
      // Attempt to categorize based on basic keyword matching
      String cat = 'Others';
      bool isInc = false;
      final lowerText = rawText.toLowerCase();
      
      if (lowerText.contains('salary') || lowerText.contains('payslip') || lowerText.contains('earning') || lowerText.contains('net pay')) {
         isInc = true;
         cat = availableIncomeCategories.isNotEmpty ? availableIncomeCategories.first : 'Earned';
      } else if (lowerText.contains('shirt') || lowerText.contains('tee') || lowerText.contains('emporium') || lowerText.contains('clothing')) {
         cat = availableExpenseCategories.firstWhere(
           (c) => c.toLowerCase() == 'shopping', 
           orElse: () => cat
         );
      }
      
      return AiReceiptResult(
        isIncome: isInc,
        reference: ref,
        amount: total,
        category: cat,
      );
    }
  }
}
